server:
  port: 9000

spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  datasource:
    name: learning
    url: jdbc:mariadb://localhost:3306/learning
    username: root
    password: 123456