CREATE TABLE IF NOT EXISTS COURSE (
    COURSE_ID INT NOT NULL AUTO_INCREMENT,
    C_NAME VARCHAR(100),
    C_DESP VARCHAR(100),
    C_FEES VARCHAR(100),
    C_RESOURCE VARCHAR(100),
    PRIMARY KEY (COURSE_ID)
);