CREATE TABLE IF NOT EXISTS USER1 (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100),
    PHONE_NO INT,
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(100),
    REG_DATE DATE,
    PASSWORD VARCHAR(100),
    UPLOAD_PHOTO VARCHAR(100),
    PRIMARY KEY (USER_ID)
);